<?php
   $_productCollection=$this->getLoadedProductCollection();//->addAttributeToSort('name', 'ASC');;
	//$_productCollection = Mage::getResourceModel('catalog/product_collection');
   //$_productCollection->clear()->addAttributeToFilter('attribute_set_id', array('eq' => 63))->load();

   $category = Mage::getModel('catalog/category');
	$tree = $category->getTreeModel();
	
	$tree->load();
	$ids = $tree->getCollection()->getAllIds();
	
   $_helper = $this->helper('catalog/output');
	
	
   $productLabelObj = $this->getLayout()->createBlock('productlabels/productlabels');
//    $rules=$productLabelObj->getRuleCollection();
//    $labels=$productLabelObj->getLabelCollection();
   
?>

<?php if(!$_productCollection->count()): ?>

<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>

<?php else: ?>

<div class="category-products">
    
    <?php echo $this->getToolbarHtml() ?>
    
    <?php // List mode ?>
   
    <?php if($this->getMode()!='grid'): ?>
    
    <?php $_iterator = 0; ?>
    
    <ol class="products-list" id="products-list">    
    <?php foreach ($_productCollection as $_product): ?>        
        <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">        	        	
        	<div style="position: relative;">													
				<?php	 
				$today = date('Y-m-d');
				//strtotime($value) < strtotime($today)
				
				//Creating Objects for label and rule collection. 
				$label= Mage::getModel ( 'productlabels/productlabels' )->getCollection();
				$rules= Mage::getResourceModel( 'productlabels/rules' );//->getCollection();
				$label_collection=$label->getData();				
              	$_labelCollection=$productLabelObj->getFormdata();
              	
              	$category = Mage::getResourceModel('catalog/category_collection')->addFieldToFilter('name', 'Cloth');
				$cat_det=$category->getData();
				$ruleCollection=Mage::getResourceModel('productlabels/rules_collection');//->addFieldToFilter('label_id', array('eq' =>406));//$label_collection[$i]['label_id'] )//);																							
						$labels=$_labelCollection->getData();					
						// 							$categoryIds = $_product->getCategoryIds();
						// 							if(count($categoryIds) ){
						// 								$firstCategoryId = $categoryIds[0];
						// 								$_category = Mage::getModel('catalog/category')->load($firstCategoryId);							
						//if ($_product->getPrice()<=300)//Name()==$cat_det[0][name])
						//$_productCollection->clear();
						//if($_product->addddAttributeToFilter('price',500)->load())						
						/*addFieldToFilter('price', array('gt' =>200)))
						 //->addFieldToFilter('label_id', array('eq' =>406));//$label_collection[$i]['label_id'] )//);*/												
						//foreach ($labels as $_label)
																													
						$storeId = Mage::app()->getStore()->getStoreId();
						
						for($j=0; $j<count($labels); $j++)
						{			    					    												
							$flag=1;
							
							$label=$labels[$j]['label_id'];
							$position= $labels[$j]['labelposition'];							
							$collection=$ruleCollection->addFieldToFilter('label_id',$label);//$_label->getData('label_id')); /*$_label->getData('label_id')*/
							$id=explode(',', "7");
							$inc=0;
							foreach ($id as $sid)
							{
								if($sid==$storeId)
									$inc++;
							}
							if($inc>0)							
							for($i=0; $i<count($collection); $i++)
							{
							 
							$attribute=$collection->getData()[$i]['attribute'];
							$label_id=$collection->getData()[$i]['label_id'];
							$condition=$collection->getData()[$i]['condition'];
							$value=$collection->getData()[$i]['value'];
																												
							$flag=$flag*1;
 							if((strtotime($today) >= strtotime($labels[$j]['fromdate'])) && (strtotime($today) <= strtotime($labels[$j]['todate'])))
							{
								
																																		
							switch($condition)
 							{
 								case "lt":
								if($flag==1)
								{
 									if($_product->getData($attribute)<$value)
									$flag=1;
								else 
									$flag=0;
								if($flag==1 && $i==count($collection)-1 && $labels[$j]['rulestatus']==1)
								{																																										
									switch($position)
									{
										case "Top-Left":
									?>
									<div style="position: absolute;z-index: 999;top: 0px;left: 0px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
									<?php break;																	
									
									case "Top-Middle":
										?>
										<div style="position: absolute;z-index: 999;top: 0px;left: 40px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
									<?php break;	
									case "Top-Right":
										?>
							 		<div style="position: absolute;z-index: 999;top: 0px;left: 80px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
									<?php break;	
									case "Middle-Left":
										?>
									<div style="position: absolute;z-index: 999;top: 40px;left: 0px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
									<?php break;	
									
									case "Middle-Middle":
										?>
										<div style="position: absolute;z-index: 999;top: 40px;left: 40px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
										<?php break;	
									
										case "Middle-Right":
											?>
											<div style="position: absolute;z-index: 999;top: 40px;left: 80px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
											<?php break;	

										case "Bottom-Left":
										?>
										<div style="position: absolute;z-index: 999;top: 80px;left: 0px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
										<?php break;	

										case "Bottom-Middle":
											?>
										<div style="position: absolute;z-index: 999;top: 80px;left: 40px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
										<?php break;	
										
										case "Bottom-Right":
											?>
										   <div style="position: absolute;z-index: 999;top: 80px;left: 80px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
										    <?php break;						
									}                                          
							}	
								}
							break;
							//check not equal to 
							case "nteq":
								if($flag==1)
								{
									if($_product->getData($attribute)!=$value)
										$flag=1;
									else
										$flag=0;
									if($flag==1 && $i==count($collection)-1 && $labels[$j]['rulestatus']==1)
									{
										switch($position)
										{
											case "Top-Left":
												?>
																<div style="position: absolute;z-index: 999;top: 0px;left: 0px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
																<?php break;																	
																
																case "Top-Middle":
																	?>
																	<div style="position: absolute;z-index: 999;top: 0px;left: 40px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
																<?php break;	
																case "Top-Right":
																	?>
														 		<div style="position: absolute;z-index: 999;top: 0px;left: 80px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
																<?php break;	
																case "Middle-Left":
																	?>
																<div style="position: absolute;z-index: 999;top: 40px;left: 0px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
																<?php break;	
																
																case "Middle-Middle":
																	?>
																	<div style="position: absolute;z-index: 999;top: 40px;left: 40px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
																	<?php break;	
																
																	case "Middle-Right":
																		?>
																		<div style="position: absolute;z-index: 999;top: 40px;left: 80px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
																		<?php break;	
							
																	case "Bottom-Left":
																	?>
																	<div style="position: absolute;z-index: 999;top: 80px;left: 0px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
																	<?php break;	
							
																	case "Bottom-Middle":
																		?>
																	<div style="position: absolute;z-index: 999;top: 80px;left: 40px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
																	<?php break;	
																	
																	case "Bottom-Right":
																		?>
																	   <div style="position: absolute;z-index: 999;top: 80px;left: 80px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
																	    <?php break;						
																}                                          
														}	
															}
														break;	
							//end not equal to 
							
							//check wether less than or equal to 
							case "lteq":
								if($flag==1)
								{
									if($_product->getData($attribute)<=$value)
										$flag=1;
									else
										$flag=0;
									if($flag==1 && $i==count($collection)-1 && $labels[$j]['rulestatus']==1)
									{
										switch($position)
										{
											case "Top-Left":
												?>
																<div style="position: absolute;z-index: 999;top: 0px;left: 0px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
																<?php break;																	
																
																case "Top-Middle":
																	?>
																	<div style="position: absolute;z-index: 999;top: 0px;left: 40px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
																<?php break;	
																case "Top-Right":
																	?>
														 		<div style="position: absolute;z-index: 999;top: 0px;left: 80px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
																<?php break;	
																case "Middle-Left":
																	?>
																<div style="position: absolute;z-index: 999;top: 40px;left: 0px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
																<?php break;	
																
																case "Middle-Middle":
																	?>
																	<div style="position: absolute;z-index: 999;top: 40px;left: 40px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
																	<?php break;	
																
																	case "Middle-Right":
																		?>
																		<div style="position: absolute;z-index: 999;top: 40px;left: 80px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
																		<?php break;	
							
																	case "Bottom-Left":
																	?>
																	<div style="position: absolute;z-index: 999;top: 80px;left: 0px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
																	<?php break;	
							
																	case "Bottom-Middle":
																		?>
																	<div style="position: absolute;z-index: 999;top: 80px;left: 40px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
																	<?php break;	
																	
																	case "Bottom-Right":
																		?>
																	   <div style="position: absolute;z-index: 999;top: 80px;left: 80px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
																	    <?php break;						
																}                                          
														}	
															}
														break;	
							
							//Check wether greater or than or equal to
							
							case "gteq":
								if($flag==1)
								{
									if($_product->getData($attribute)>=$value)
										$flag=1;
									else
										$flag=0;
									if($flag==1 && $i==count($collection)-1 && $labels[$j]['rulestatus']==1)
									{
										switch($position)
										{
											case "Top-Left":
												?>
												<div style="position: absolute;z-index: 999;top: 0px;left: 0px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
													<?php break;																	
															
												case "Top-Middle":
													?>
												<div style="position: absolute;z-index: 999;top: 0px;left: 40px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
												<?php break;	
													case "Top-Right":
															?>
												<div style="position: absolute;z-index: 999;top: 0px;left: 80px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
												<?php break;	
												case "Middle-Left":
												?>
												<div style="position: absolute;z-index: 999;top: 40px;left: 0px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
																<?php break;	
																
																case "Middle-Middle":
																	?>
																	<div style="position: absolute;z-index: 999;top: 40px;left: 40px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
																	<?php break;	
																
																	case "Middle-Right":
																		?>
																		<div style="position: absolute;z-index: 999;top: 40px;left: 80px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
																		<?php break;	
							
																	case "Bottom-Left":
																	?>
																	<div style="position: absolute;z-index: 999;top: 80px;left: 0px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
																	<?php break;	
							
																	case "Bottom-Middle":
																		?>
																	<div style="position: absolute;z-index: 999;top: 80px;left: 40px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
																	<?php break;	
																	
																	case "Bottom-Right":
																		?>
																	   <div style="position: absolute;z-index: 999;top: 80px;left: 80px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
																	    <?php break;						
																}                                          
														}	
															}
														break;	
							
							//end greater or than or equal to
							case "gt":
								if($flag==1)
								{
								if($_product->getData($attribute)>$value)
									$flag=1;
								else
									$flag=0;
								if($flag==1  && $i==count($collection)-1 && $labels[$j]['rulestatus']==1)//count($collection)-1)
								{
								switch($position)
									{
										case "Top-Left":
									?>
									<div style="position: absolute;z-index: 999;top: 0px;left: 0px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
									<?php break;																	
									
									case "Top-Middle":
										?>
										<div style="position: absolute;z-index: 999;top: 0px;left: 40px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
									<?php break;	
									case "Top-Right":
										?>
							 		<div style="position: absolute;z-index: 999;top: 0px;left: 80px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
									<?php break;	
									case "Middle-Left":
										?>
									<div style="position: absolute;z-index: 999;top: 40px;left: 0px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
									<?php break;	
									
									case "Middle-Middle":
										?>
										<div style="position: absolute;z-index: 999;top: 40px;left: 40px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
										<?php break;	
									
										case "Middle-Right":
											?>
											<div style="position: absolute;z-index: 999;top: 40px;left: 80px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
											<?php break;	

										case "Bottom-Left":
										?>
										<div style="position: absolute;z-index: 999;top: 80px;left: 0px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
										<?php break;	

										case "Bottom-Middle":
											?>
										<div style="position: absolute;z-index: 999;top: 80px;left: 40px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
										<?php break;	
										
										case "Bottom-Right":
											?>
										   <div style="position: absolute;z-index: 999;top: 80px;left: 80px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
										    <?php break;						
									}                                              
									}
								}	
									break;								
							case "eq":
								if($flag==1)
								{ 																	
								if($attribute=="Availability")
								{								
									if($value==0)
									{	
										if(!$_product->isAvailable())
										{	
										switch($position)
										{
										case "Top-Left":
									?>
									<div style="position: absolute;z-index: 999;top: 0px;left: 0px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
									<?php break;																	
									
									case "Top-Middle":
										?>
										<div style="position: absolute;z-index: 999;top: 0px;left: 40px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
									<?php break;	
									case "Top-Right":
										?>
							 		<div style="position: absolute;z-index: 999;top: 0px;left: 80px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
									<?php break;	
									case "Middle-Left":
										?>
									<div style="position: absolute;z-index: 999;top: 40px;left: 0px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
									<?php break;	
									
									case "Middle-Middle":
										?>
										<div style="position: absolute;z-index: 999;top: 40px;left: 40px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
										<?php break;	
									
										case "Middle-Right":
											?>
											<div style="position: absolute;z-index: 999;top: 40px;left: 80px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
											<?php break;	

										case "Bottom-Left":
										?>
										<div style="position: absolute;z-index: 999;top: 80px;left: 0px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
										<?php break;	

										case "Bottom-Middle":
											?>
										<div style="position: absolute;z-index: 999;top: 80px;left: 40px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
										<?php break;	
										
										case "Bottom-Right":
											?>
										   <div style="position: absolute;z-index: 999;top: 80px;left: 80px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
										    <?php break;						
									}                   
											}
										}else 
										{
											if($_product->isAvailable())
											{	switch($position)
									{
										case "Top-Left":
									?>
									<div style="position: absolute;z-index: 999;top: 0px;left: 0px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
									<?php break;																	
									
									case "Top-Middle":
										?>
										<div style="position: absolute;z-index: 999;top: 0px;left: 40px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
									<?php break;	
									case "Top-Right":
										?>
							 		<div style="position: absolute;z-index: 999;top: 0px;left: 80px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
									<?php break;	
									case "Middle-Left":
										?>
									<div style="position: absolute;z-index: 999;top: 40px;left: 0px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
									<?php break;	
									
									case "Middle-Middle":
										?>
										<div style="position: absolute;z-index: 999;top: 40px;left: 40px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
										<?php break;	
									
										case "Middle-Right":
											?>
											<div style="position: absolute;z-index: 999;top: 40px;left: 80px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
											<?php break;	

										case "Bottom-Left":
										?>
										<div style="position: absolute;z-index: 999;top: 80px;left: 0px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
										<?php break;	

										case "Bottom-Middle":
											?>
										<div style="position: absolute;z-index: 999;top: 80px;left: 40px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
										<?php break;	
										
										case "Bottom-Right":
											?>
										   <div style="position: absolute;z-index: 999;top: 80px;left: 80px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
										    <?php break;						
									}                   
											}
										}
									}		
									if($attribute=="category")
									{
										$categoryIds = $_product->getCategoryIds();
										if(count($categoryIds))
									    {
											$firstCategoryId = $categoryIds[0];
											$_category = Mage::getModel('catalog/category')->load($firstCategoryId);
											if($_category->getData('name')==$value)																						
												$flag=1;											 
											else
												$flag=0;												
										}	
										//$_category->clearInstance();	
									}
																	
									else
									{									
										if($_product->getData($attribute)==$value)
										{
										$flag=1;
										}
										else
											$flag=0;//
									}
								if($flag==1  && $i==count($collection)-1 && $labels[$j]['rulestatus']==1)//count($collection)-1)
								{										
									switch($position)
									{
										case "Top-Left":
									?>
									<div style="position: absolute;z-index: 999;top: 0px;left: 0px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
									<?php break;																	
									
									case "Top-Middle":
										?>
										<div style="position: absolute;z-index: 999;top: 0px;left: 40px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
									<?php break;	
									case "Top-Right":
										?>
							 		<div style="position: absolute;z-index: 999;top: 0px;left: 80px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
									<?php break;	
									case "Middle-Left":
										?>
									<div style="position: absolute;z-index: 999;top: 40px;left: 0px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
									<?php break;	
									
									case "Middle-Middle":
										?>
										<div style="position: absolute;z-index: 999;top: 40px;left: 40px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
										<?php break;	
									
										case "Middle-Right":
											?>
											<div style="position: absolute;z-index: 999;top: 40px;left: 80px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
											<?php break;	

										case "Bottom-Left":
										?>
										<div style="position: absolute;z-index: 999;top: 80px;left: 0px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
										<?php break;	

										case "Bottom-Middle":
											?>
										<div style="position: absolute;z-index: 999;top: 80px;left: 40px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
										<?php break;	
										
										case "Bottom-Right":
											?>
										   <div style="position: absolute;z-index: 999;top: 80px;left: 80px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
										    <?php break;						
									}                          
								}	
								}break;
 							}
							
							}
							
							}
							$collection->clear()
							->getSelect()->reset('where');
							
							
								}?>			
																																			
				<?php // Product Image ?>				
				<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
			
			</div>
                   
            <?php // Product description ?>
            
            <div class="product-shop">
                
                <div class="f-fix">
                    
                    <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                   
                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
                   
                    <?php if($_product->getRatingSummary()): ?>
                    
                    <?php echo $this->getReviewsSummaryHtml($_product) ?>
                    
                    <?php endif; ?>
                    
                    <?php echo $this->getPriceHtml($_product, true) ?>
                    
                    <?php if($_product->isSaleable()): ?>
                       
                        <p><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
                    
                    <?php else: ?>
                     
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                  
                    <?php endif; ?>
                   
                    <div class="desc std">
                      
                        <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                      
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
                   
                    </div>
                    
                    <ul class="add-to-links">
                       
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                        
                            <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                       
                        <?php endif; ?>
                       
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                          
                            <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                       
                        <?php endif; ?>
                   
                    </ul>
                
                </div>
            
            </div>
        
        </li>
    
    <?php endforeach; ?>
    
    </ol>
   
    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>
   
    <?php else: ?>

    
    <?php // Grid Mode ?>
    
    <?php $_collectionSize = $_productCollection->count(); ?>
    
    <?php $_columnCount = $this->getColumnCount(); ?>
    
    <?php $i=0; foreach ($_productCollection as $_product): ?>
			
			<?php if ($i++%$_columnCount==0): ?>
			
			<ul class="products-grid">
			
			<?php endif ?>
				
				<li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
					
					<div style="position: relative;">
					<?php 

					
					$label= Mage::getModel ( 'productlabels/productlabels' )->getCollection();
					$rules= Mage::getResourceModel( 'productlabels/rules' );//->getCollection();
					$label_collection=$label->getData();
					$_labelCollection=$productLabelObj->getFormdata();
					 
					$category = Mage::getResourceModel('catalog/category_collection')->addFieldToFilter('name', 'Cloth');
					$cat_det=$category->getData();
					$ruleCollection=Mage::getResourceModel('productlabels/rules_collection');//->addFieldToFilter('label_id', array('eq' =>406));//$label_collection[$i]['label_id'] )//);
						
					$labels=$_labelCollection->getData();
					
					for($j=0; $j<count($labels); $j++)
						{			    					    												
							$flag=1;
							
							$label=$labels[$j]['label_id'];
							$position= $labels[$j]['labelposition'];							
							$collection=$ruleCollection->addFieldToFilter('label_id',$label);//$_label->getData('label_id')); /*$_label->getData('label_id')*/
							
							for($i=0; $i<count($collection); $i++)
							{
							 
							$attribute=$collection->getData()[$i]['attribute'];
							$label_id=$collection->getData()[$i]['label_id'];
							$condition=$collection->getData()[$i]['condition'];
							$value=$collection->getData()[$i]['value'];
														
 							$flag=$flag*1;
 							switch($condition)
 							{
 								case "lt":
								if($flag==1)
								{
 									if($_product->getData($attribute)<$value)
									$flag=1;
								else 
									$flag=0;
								if($flag==1 && $i==count($collection)-1)
								{														
									switch($position)
									{
									case "Top-Left":
									?>
									<div style="position: absolute;z-index: 999;top: 0px;left: 0px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
									
									<?php break;																	
									
									case "Top-Middle":
										?>
										<div style="position: absolute;z-index: 999;top: 0px;left: 40px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
									<?php break;	
									case "Top-Right":
										?>
							 		<div style="position: absolute;z-index: 999;top: 0px;left: 80px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
									<?php break;	
									case "Middle-Left":
										?>
									<div style="position: absolute;z-index: 999;top: 40px;left: 0px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
									<?php break;	
									
									case "Middle-Middle":
										?>
										<div style="position: absolute;z-index: 999;top: 40px;left: 40px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
										<?php break;	
									
										case "Middle-Right":
											?>
											<div style="position: absolute;z-index: 999;top: 40px;left: 80px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
											<?php break;	

										case "Bottom-Left":
										?>
										<div style="position: absolute;z-index: 999;top: 80px;left: 0px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
										<?php break;	

										case "Bottom-Middle":
											?>
										<div style="position: absolute;z-index: 999;top: 80px;left: 40px;"><?php  ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
										<?php break;	
										
										case "Bottom-Right":
											?>
										   <div style="position: absolute;z-index: 999;top: 80px;left: 80px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
										    <?php break;						
									}                                          
							}	
								}
							break;	
							case "gt":
								if($flag==1)
								{
								if($_product->getData($attribute)>$value)
									$flag=1;
								else
									$flag=0;
								if($flag==1  && $i==count($collection)-1)//count($collection)-1)
								{
								switch($position)
									{
										case "Top-Left":
									?>
									<div style="position: absolute;z-index: 999;top: 0px;left: 0px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
									<?php break;																	
									
									case "Top-Middle":
										?>
										<div style="position: absolute;z-index: 999;top: 0px;left: 40px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
									<?php break;	
									case "Top-Right":
										?>
							 		<div style="position: absolute;z-index: 999;top: 0px;left: 80px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
									<?php break;	
									case "Middle-Left":
										?>
									<div style="position: absolute;z-index: 999;top: 40px;left: 0px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
									<?php break;	
									
									case "Middle-Middle":
										?>
										<div style="position: absolute;z-index: 999;top: 40px;left: 40px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
										<?php break;	
									
										case "Middle-Right":
											?>
											<div style="position: absolute;z-index: 999;top: 40px;left: 80px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
											<?php break;	

										case "Bottom-Left":
										?>
										<div style="position: absolute;z-index: 999;top: 80px;left: 0px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
										<?php break;	

										case "Bottom-Middle":
											?>
										<div style="position: absolute;z-index: 999;top: 80px;left: 40px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
										<?php break;	
										
										case "Bottom-Right":
											?>
										   <div style="position: absolute;z-index: 999;top: 80px;left: 80px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
										    <?php break;						
									}                                              
									}
								}	
									break;		
									//check not equal to
									case "nteq":
										if($flag==1)
										{
											if($_product->getData($attribute)!=$value)
												$flag=1;
											else
												$flag=0;
											if($flag==1 && $i==count($collection)-1 && $labels[$j]['rulestatus']==1)
											{
												switch($position)
												{
													case "Top-Left":
														?>
																									<div style="position: absolute;z-index: 999;top: 0px;left: 0px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
																									<?php break;																	
																									
																									case "Top-Middle":
																										?>
																										<div style="position: absolute;z-index: 999;top: 0px;left: 40px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
																									<?php break;	
																									case "Top-Right":
																										?>
																							 		<div style="position: absolute;z-index: 999;top: 0px;left: 80px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
																									<?php break;	
																									case "Middle-Left":
																										?>
																									<div style="position: absolute;z-index: 999;top: 40px;left: 0px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
																									<?php break;	
																									
																									case "Middle-Middle":
																										?>
																										<div style="position: absolute;z-index: 999;top: 40px;left: 40px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
																										<?php break;	
																									
																										case "Middle-Right":
																											?>
																											<div style="position: absolute;z-index: 999;top: 40px;left: 80px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
																											<?php break;	
																
																										case "Bottom-Left":
																										?>
																										<div style="position: absolute;z-index: 999;top: 80px;left: 0px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
																										<?php break;	
																
																										case "Bottom-Middle":
																											?>
																										<div style="position: absolute;z-index: 999;top: 80px;left: 40px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
																										<?php break;	
																										
																										case "Bottom-Right":
																											?>
																										   <div style="position: absolute;z-index: 999;top: 80px;left: 80px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
																										    <?php break;						
																									}                                          
																							}	
																								}
																							break;	
																//end not equal to 
																
																//check wether less than or equal to 
																case "lteq":
																	if($flag==1)
																	{
																		if($_product->getData($attribute)<=$value)
																			$flag=1;
																		else
																			$flag=0;
																		if($flag==1 && $i==count($collection)-1 && $labels[$j]['rulestatus']==1)
																		{
																			switch($position)
																			{
																				case "Top-Left":
																					?>
																									<div style="position: absolute;z-index: 999;top: 0px;left: 0px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
																									<?php break;																	
																									
																									case "Top-Middle":
																										?>
																										<div style="position: absolute;z-index: 999;top: 0px;left: 40px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
																									<?php break;	
																									case "Top-Right":
																										?>
																							 		<div style="position: absolute;z-index: 999;top: 0px;left: 80px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
																									<?php break;	
																									case "Middle-Left":
																										?>
																									<div style="position: absolute;z-index: 999;top: 40px;left: 0px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
																									<?php break;	
																									
																									case "Middle-Middle":
																										?>
																										<div style="position: absolute;z-index: 999;top: 40px;left: 40px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
																										<?php break;	
																									
																										case "Middle-Right":
																											?>
																											<div style="position: absolute;z-index: 999;top: 40px;left: 80px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
																											<?php break;	
																
																										case "Bottom-Left":
																										?>
																										<div style="position: absolute;z-index: 999;top: 80px;left: 0px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
																										<?php break;	
																
																										case "Bottom-Middle":
																											?>
																										<div style="position: absolute;z-index: 999;top: 80px;left: 40px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
																										<?php break;	
																										
																										case "Bottom-Right":
																											?>
																										   <div style="position: absolute;z-index: 999;top: 80px;left: 80px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
																										    <?php break;						
																									}                                          
																							}	
																								}
																							break;	
																
																//Check wether greater or than or equal to
																
																case "gteq":
																	if($flag==1)
																	{
																		if($_product->getData($attribute)>=$value)
																			$flag=1;
																		else
																			$flag=0;
																		if($flag==1 && $i==count($collection)-1 && $labels[$j]['rulestatus']==1)
																		{
																			switch($position)
																			{
																				case "Top-Left":
																					?>
																					<div style="position: absolute;z-index: 999;top: 0px;left: 0px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
																						<?php break;																	
																								
																					case "Top-Middle":
																						?>
																					<div style="position: absolute;z-index: 999;top: 0px;left: 40px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
																					<?php break;	
																						case "Top-Right":
																								?>
																					<div style="position: absolute;z-index: 999;top: 0px;left: 80px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
																					<?php break;	
																					case "Middle-Left":
																					?>
																					<div style="position: absolute;z-index: 999;top: 40px;left: 0px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
																									<?php break;	
																									
																									case "Middle-Middle":
																										?>
																										<div style="position: absolute;z-index: 999;top: 40px;left: 40px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
																										<?php break;	
																									
																										case "Middle-Right":
																											?>
																											<div style="position: absolute;z-index: 999;top: 40px;left: 80px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
																											<?php break;	
																
																										case "Bottom-Left":
																										?>
																										<div style="position: absolute;z-index: 999;top: 80px;left: 0px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
																										<?php break;	
																
																										case "Bottom-Middle":
																											?>
																										<div style="position: absolute;z-index: 999;top: 80px;left: 40px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
																										<?php break;	
																										
																										case "Bottom-Right":
																											?>
																										   <div style="position: absolute;z-index: 999;top: 80px;left: 80px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
																										    <?php break;						
																									}                                          
																							}	
																								}
																							break;	
																
																//end greater or than or equal to
																		
							case "eq":
								if($flag==1)
								{
									if($attribute=="Availability")
								{								
									if($value==0)
									{	
										if(!$_product->isAvailable())
										{	
										switch($position)
										{
										case "Top-Left":
									?>
									<div style="position: absolute;z-index: 999;top: 0px;left: 0px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
									<?php break;																	
									
									case "Top-Middle":
										?>
										<div style="position: absolute;z-index: 999;top: 0px;left: 40px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
									<?php break;	
									case "Top-Right":
										?>
							 		<div style="position: absolute;z-index: 999;top: 0px;left: 80px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
									<?php break;	
									case "Middle-Left":
										?>
									<div style="position: absolute;z-index: 999;top: 40px;left: 0px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
									<?php break;	
									
									case "Middle-Middle":
										?>
										<div style="position: absolute;z-index: 999;top: 40px;left: 40px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
										<?php break;	
									
										case "Middle-Right":
											?>
											<div style="position: absolute;z-index: 999;top: 40px;left: 80px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
											<?php break;	

										case "Bottom-Left":
										?>
										<div style="position: absolute;z-index: 999;top: 80px;left: 0px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
										<?php break;	

										case "Bottom-Middle":
											?>
										<div style="position: absolute;z-index: 999;top: 80px;left: 40px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
										<?php break;	
										
										case "Bottom-Right":
											?>
										   <div style="position: absolute;z-index: 999;top: 80px;left: 80px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
										    <?php break;						
									}                   
											}
										}else 
										{
											if($_product->isAvailable())
											{	switch($position)
									{
										case "Top-Left":
									?>
									<div style="position: absolute;z-index: 999;top: 0px;left: 0px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
									<?php break;																	
									
									case "Top-Middle":
										?>
										<div style="position: absolute;z-index: 999;top: 0px;left: 40px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
									<?php break;	
									case "Top-Right":
										?>
							 		<div style="position: absolute;z-index: 999;top: 0px;left: 80px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
									<?php break;	
									case "Middle-Left":
										?>
									<div style="position: absolute;z-index: 999;top: 40px;left: 0px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
									<?php break;	
									
									case "Middle-Middle":
										?>
										<div style="position: absolute;z-index: 999;top: 40px;left: 40px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
										<?php break;	
									
										case "Middle-Right":
											?>
											<div style="position: absolute;z-index: 999;top: 40px;left: 80px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
											<?php break;	

										case "Bottom-Left":
										?>
										<div style="position: absolute;z-index: 999;top: 80px;left: 0px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
										<?php break;	

										case "Bottom-Middle":
											?>
										<div style="position: absolute;z-index: 999;top: 80px;left: 40px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
										<?php break;	
										
										case "Bottom-Right":
											?>
										   <div style="position: absolute;z-index: 999;top: 80px;left: 80px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
										    <?php break;						
									}                   
											}
										}
									}		
									if($attribute=="category")
									{
										$categoryIds = $_product->getCategoryIds();
										if(count($categoryIds))
									    {
											$firstCategoryId = $categoryIds[0];
											$_category = Mage::getModel('catalog/category')->load($firstCategoryId);
											if($_category->getData('name')==$value)																						
												$flag=1;											 
											else
												$flag=0;												
										}	
										//$_category->clearInstance();	
									}
																	
									else
									{									
										if($_product->getData($attribute)==$value)
										{
										$flag=1;
										}
										else
											$flag=0;//
									}
								if($flag==1  && $i==count($collection)-1)//count($collection)-1)
								{										
									switch($position)
									{
										case "Top-Left":
									?>
									<div style="position: absolute;z-index: 999;top: 0px;left: 0px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
									<?php break;																	
									
									case "Top-Middle":
										?>
										<div style="position: absolute;z-index: 999;top: 0px;left: 40px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
									<?php break;	
									case "Top-Right":
										?>
							 		<div style="position: absolute;z-index: 999;top: 0px;left: 80px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
									<?php break;	
									case "Middle-Left":
										?>
									<div style="position: absolute;z-index: 999;top: 40px;left: 0px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
									<?php break;	
									
									case "Middle-Middle":
										?>
										<div style="position: absolute;z-index: 999;top: 40px;left: 40px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
										<?php break;	
									
										case "Middle-Right":
											?>
											<div style="position: absolute;z-index: 999;top: 40px;left: 80px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
											<?php break;	

										case "Bottom-Left":
										?>
										<div style="position: absolute;z-index: 999;top: 80px;left: 0px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
										<?php break;	

										case "Bottom-Middle":
											?>
										<div style="position: absolute;z-index: 999;top: 80px;left: 40px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
										<?php break;	
										
										case "Bottom-Right":
											?>
										   <div style="position: absolute;z-index: 999;top: 80px;left: 80px;"><?php ?><img alt="" src="<?php echo Mage::getBaseUrl('media').$labels[$j]['filename'].' '; ?>" /></div>				
										    <?php break;						
									}                          
								}	
								}break;
 							}
						
 							
							}
							
							$collection->clear()
							->getSelect()->reset('where');
								}?>			
					
				
			
											
			        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
						</div>
					
					
					<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
					
					<?php if($_product->getRatingSummary()): ?>
					
					<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
					
					<?php endif; ?>
					
					<?php echo $this->getPriceHtml($_product, true) ?>
					
					<div class="actions">
						
					<?php if($_product->isSaleable()): ?>
						
					<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
						
						<?php else: ?>
							
							<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
						
						<?php endif; ?>
						
						<ul class="add-to-links">
							
							<?php if ($this->helper('wishlist')->isAllow()) : ?>
								
								<li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
							
							<?php  endif;  ?>
							
							<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
								
								<li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
								
							<?php endif; ?>
						
						</ul>
					
					</div>
				
			</li>
				
			<?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
			
		</ul>
        
        <?php endif ?>
        
        <?php endforeach ?>
       
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
    
    <?php endif; ?>

    <div class="toolbar-bottom">
       
        <?php echo $this->getToolbarHtml() ?>
   
    </div>

    </div>

<?php endif; ?>
